export const ADD_DEFAULT_FILTER = 'ADD_DEFAULT_FILTER';
export const DELETE_DEFAULT_FILTER = 'DELETE_DEFAULT_FILTER';

export const ADD_CUSTOM_POINT = 'ADD_CUSTOM_POINT';
export const DELETE_CUSTOM_POINT = 'DELETE_CUSTOM_POINT';